POST http://localhost:3000/produtos
Content-Type: application/json 

{
    "nome" : "CD da xuxa invertido",
    "preco" : 150000,
    "categoria" : "produtos-lendarios"
}

###

GET http://localhost:3000/produtos
